dotenv      : statement
            | statement "\n" dotenv
            | "\n"
            ;

statement   : "export" expression
            | expression
            ;

expression  : key "=" value
            | key ":" value
            ;

key         : identifier
            | string
            ;

value       : text
            | string
            ;

identifier  : id-head id-chars
            ;

text        : string
            | chars
            ;

string      : '"' [ any-chars ] '"'
            | "'" [ any-chars ] "'"
            ;
